"""Public package exports for :mod:`atomref`."""

from .__about__ import __version__
from .elements import (
    Element,
    canonicalize_element_symbol,
    get_element,
    iter_elements,
    is_valid_element_symbol,
)
from .policy import LookupResult, ValuePolicy, get_value, lookup_value
from .radii import (
    DEFAULT_COVALENT_POLICY,
    DEFAULT_VDW_POLICY,
    RadiiElementAssessment,
    RadiiPolicy,
    RadiiPolicyAssessment,
    assess_radii_policy,
    get_covalent_radius,
    get_radii_set,
    get_radii_set_info,
    get_vdw_radius,
    list_radii_set_infos,
    list_radii_sets,
    lookup_covalent_radius,
    lookup_vdw_radius,
)
from .xh import (
    DEFAULT_XH_POLICY,
    XHPolicy,
    get_xh_bond_length,
    get_xh_set,
    get_xh_set_info,
    list_xh_set_infos,
    list_xh_sets,
    lookup_xh_bond_length,
)
from .registry import (
    CoverageInfo,
    DatasetInfo,
    DatasetRef,
    ElementScalarSet,
    QuantityInfo,
    Reference,
    get_builtin_set,
    get_dataset_info,
    get_quantity_info,
    list_dataset_ids,
    list_dataset_infos,
    list_quantities,
)
from .transfer import LinearFit, LinearTransfer, SubstitutionTransfer

__all__ = [
    "__version__",
    "Element",
    "canonicalize_element_symbol",
    "get_element",
    "iter_elements",
    "is_valid_element_symbol",
    "CoverageInfo",
    "DatasetInfo",
    "DatasetRef",
    "ElementScalarSet",
    "QuantityInfo",
    "Reference",
    "get_builtin_set",
    "get_dataset_info",
    "get_quantity_info",
    "list_dataset_ids",
    "list_dataset_infos",
    "list_quantities",
    "LinearFit",
    "LinearTransfer",
    "SubstitutionTransfer",
    "LookupResult",
    "ValuePolicy",
    "lookup_value",
    "get_value",
    "RadiiPolicy",
    "RadiiElementAssessment",
    "RadiiPolicyAssessment",
    "DEFAULT_COVALENT_POLICY",
    "DEFAULT_VDW_POLICY",
    "list_radii_sets",
    "list_radii_set_infos",
    "get_radii_set",
    "get_radii_set_info",
    "lookup_covalent_radius",
    "get_covalent_radius",
    "lookup_vdw_radius",
    "get_vdw_radius",
    "assess_radii_policy",
    "XHPolicy",
    "DEFAULT_XH_POLICY",
    "list_xh_sets",
    "list_xh_set_infos",
    "get_xh_set",
    "get_xh_set_info",
    "lookup_xh_bond_length",
    "get_xh_bond_length",
]
